---
- hosts: localhost
  user: bcox
  tasks:
    - name: link dotfiles to home
      file: src={{ dotfiles }}/{{ item.src }} dest=~/.{{ item.dest }} state=link
      with_items:
        - { src: 'Xresources',       dest: 'Xresources' }
        - { src: 'bash_profile',     dest: 'bash_profile' }
        - { src: 'bashrc',           dest: 'bashrc' }
        - { src: 'dircolors',        dest: 'dircolors' }
        - { src: 'editorconfig',     dest: 'editorconfig' }
        - { src: 'elisp',            dest: 'elisp' }
        - { src: 'emacs',            dest: 'emacs' }
        - { src: 'gitconfig',        dest: 'gitconfig' }
        - { src: 'gitignore',        dest: 'gitignore.global' }
        - { src: 'inputrc',          dest: 'inputrc' }
        - { src: 'iterm2_tmux.conf', dest: 'iterm2_tmux.conf' }
        - { src: 'screenrc',         dest: 'screenrc' }
        - { src: 'scriptlib',        dest: 'scriptlib' }
        - { src: 'zshenv',           dest: 'zshenv' }
        - { src: 'zshrc',            dest: 'zshrc' }
        - { src: 'zprofile',         dest: 'zprofile' }
        - { src: 'zpreztorc',        dest: 'zpreztorc' }
        - { src: 'prezto',           dest: 'zprezto' }
    - name: create .zinit.d directory
      file: path=~/.zinit.d state=directory
    - name: link zinit.d files to home
      file: src={{ dotfiles }}/zinit.d/{{ item.src }} dest=~/.zinit.d/{{ item.dest }} state=link
      with_items:
        - { src: '20scriptlib',                 dest: '20scriptlib' }
        - { src: '35gopath',                    dest: '35gopath' }
        - { src: '50pythonpath',                dest: '50pythonpath' }
        - { src: '90prezto',                    dest: '90prezto' }
        - { src: '91dircolors',                 dest: '91dircolors' }
        - { src: '99_iterm2_shell_integration', dest: '99_iterm2_shell_integration' }
    - name: create bin directory
      file: path=~/bin state=directory
    - name: link bin files into home
      file: src={{ dotfiles }}/bin/{{ item.src }} dest=~/bin/{{ item.dest }} state=link
      with_items:
        - { src: 'python',               dest: 'python' }
        - { src: 'launch',               dest: 'launch' }
        - { src: 'ctw',                  dest: 'ctw' }
        - { src: 'gbv',                  dest: 'gbv' }
        - { src: 'signal',               dest: 'signal' }
        - { src: 'waitfor',              dest: 'waitfor' }
        - { src: 'check_workspaces',     dest: 'check_workspaces' }
        - { src: 'git_workspace_status', dest: 'git_workspace_status' }
        - { src: 'git-new-workdir',      dest: 'git-new-workdir' }
