---
- hosts: localhost
  user: bcox
  tasks:
    - name: link ... to dotfile repo
      file: src={{ dotfiles }} dest=~/... state=link

    - name: link dotfiles to home
      file: src=.../{{ item.src }} dest=~/.{{ item.dest }} state=link
      with_items:
        - { src: 'bash_profile',     dest: 'bash_profile' }
        - { src: 'bashrc',           dest: 'bashrc' }
        - { src: 'dircolors',        dest: 'dircolors' }
        - { src: 'editorconfig',     dest: 'editorconfig' }
        - { src: 'elisp',            dest: 'elisp' }
        - { src: 'gitconfig',        dest: 'gitconfig' }
        - { src: 'gitignore.global', dest: 'gitignore.global' }
        - { src: 'inputrc',          dest: 'inputrc' }
        - { src: 'scriptlib',        dest: 'scriptlib' }
        - { src: 'tmux.conf',        dest: 'tmux.conf' }
        - { src: 'tmux',             dest: 'tmux' }
        - { src: 'vim',              dest: 'vim' }
        - { src: 'zshrc',            dest: 'zshrc' }

    - name: copy .emacs to home
      copy: src={{ dotfiles }}/emacs dest=~/.emacs backup=true

    - name: create .local/share/shell
      file: path=~/.local/share/shell state=directory

    - name: create .init.d directory
      file: path=~/.init.d state=directory
    - name: link ~/.init.d/... to repo
      file: src=../.../init.d dest=~/.init.d/... state=link
    - name: link init.d files to home
      file: src=.../{{ item.src }} dest=~/.init.d/{{ item.dest }} state=link
      with_items:
        - { src: '00locale',                    dest: '00locale' }
        - { src: '00path',                      dest: '00path' }
        - { src: '01editor',                    dest: '01editor' }
        - { src: '02env',                       dest: '02env' }
        - { src: '03history',                   dest: '03history' }
        - { src: '10detect_ide',                dest: '10detect_ide' }
        - { src: '20scriptlib',                 dest: '20scriptlib' }
        - { src: '35gopath',                    dest: '35gopath' }
        - { src: '51ansible',                   dest: '51ansible' }
        - { src: '51cargo',                     dest: '51cargo' }
        - { src: '51nvm',                       dest: '51nvm' }
        - { src: '55direnv',                    dest: '55direnv' }
        - { src: '91dircolors',                 dest: '91dircolors' }
        - { src: '94aliases',                   dest: '94aliases' }

    - name: create bin directory
      file: path=~/.local/bin state=directory
    - name: link bin files into home
      file: src={{ dotfiles }}/bin/{{ item.src }} dest=~/.local/bin/{{ item.dest }} state=link
      with_items:
        - { src: 'launch',               dest: 'launch' }
        - { src: 'ctw',                  dest: 'ctw' }
        - { src: 'gbv',                  dest: 'gbv' }
        - { src: 'signal',               dest: 'signal' }
        - { src: 'waitfor',              dest: 'waitfor' }
