---
- hosts: localhost
  user: bcox
  tasks:
    - name: link ... to dotfile repo
      file: src={{ dotfiles }} dest=~/... state=link
    - name: link dotfiles to home
      file: src=.../{{ item.src }} dest=~/.{{ item.dest }} state=link
      with_items:
        - { src: 'bash_profile',     dest: 'bash_profile' }
        - { src: 'bashrc',           dest: 'bashrc' }
        - { src: 'dircolors',        dest: 'dircolors' }
        - { src: 'editorconfig',     dest: 'editorconfig' }
        - { src: 'elisp',            dest: 'elisp' }
        - { src: 'gitconfig',        dest: 'gitconfig' }
        - { src: 'gitignore.global', dest: 'gitignore.global' }
        - { src: 'inputrc',          dest: 'inputrc' }
        - { src: 'scriptlib',        dest: 'scriptlib' }
        - { src: 'tmux.conf',        dest: 'tmux.conf' }
        - { src: 'tmux',             dest: 'tmux' }
        - { src: 'vim',              dest: 'vim' }
        - { src: 'zshenv',           dest: 'zshenv' }
        - { src: 'zshrc',            dest: 'zshrc' }
    - name: copy .emacs to home
      copy: src={{ dotfiles }}/emacs dest=~/.emacs backup=true
    - name: create .zinit.d directory
      file: path=~/.zinit.d state=directory
    - name: link zinit.d/... to repo
      file: src=../.../zinit.d dest=~/.zinit.d/... state=link
    - name: link zinit.d files to home
      file: src=.../{{ item.src }} dest=~/.zinit.d/{{ item.dest }} state=link
      with_items:
        - { src: '10detect_ide',                dest: '10detect_ide' }
        - { src: '20scriptlib',                 dest: '20scriptlib' }
        - { src: '35gopath',                    dest: '35gopath' }
        - { src: '40homebrew',                  dest: '40homebrew' }
        - { src: '51nvm',                       dest: '51nvm' }
        - { src: '55direnv',                    dest: '55direnv' }
        - { src: '90prezto',                    dest: '90prezto' }
        - { src: '91dircolors',                 dest: '91dircolors' }
    - name: create bin directory
      file: path=~/.local/bin state=directory
    - name: link bin files into home
      file: src={{ dotfiles }}/bin/{{ item.src }} dest=~/.local/bin/{{ item.dest }} state=link
      with_items:
        - { src: 'launch',               dest: 'launch' }
        - { src: 'ctw',                  dest: 'ctw' }
        - { src: 'gbv',                  dest: 'gbv' }
        - { src: 'signal',               dest: 'signal' }
        - { src: 'waitfor',              dest: 'waitfor' }
